#!/usr/bin/env python3

import rclpy
from rclpy.node import Node
from geometry_msgs.msg import Twist
import time


class UINode(Node):

    def __init__(self):
        super().__init__('ui_node')

        self.pub_robot1 = self.create_publisher(Twist, '/robot1/cmd_vel', 10)
        self.pub_robot2 = self.create_publisher(Twist, '/robot2/cmd_vel', 10)

        self.get_logger().info("UI node started")

    def send_command(self, robot, lin, ang):
        msg = Twist()
        msg.linear.x = lin
        msg.angular.z = ang

        publisher = self.pub_robot1 if robot == 1 else self.pub_robot2

        start = time.time()
        while time.time() - start < 1.0:
            publisher.publish(msg)
            time.sleep(0.1)

        # stop robot
        stop_msg = Twist()
        publisher.publish(stop_msg)
        self.get_logger().info(f"Robot {robot} stopped")


def main(args=None):
    rclpy.init(args=args)
    node = UINode()

    try:
        while rclpy.ok():
            robot = int(input("Select robot (1 or 2): "))
            lin = float(input("Linear velocity: "))
            ang = float(input("Angular velocity: "))
            node.send_command(robot, lin, ang)
    except KeyboardInterrupt:
        pass

    node.destroy_node()
    rclpy.shutdown()


if __name__ == '__main__':
    main()
